### ISSUE TITLE
Product carousel

### ISSUE THREAD

**Issue by chelseafischerlodike** [chelseafischerlodike/CKMK-Digital-Bella#100]
Pate trays need to be smaller than the dry bags

**Comment by peak9ine** [comment]
@chelseafischerlodike @DevStL  Is this code related, or do we need specs outlined for John and a production artists to update assets for the site?

**Comment by DevStL** [comment]
lets discuss this as a group. i can adjust the sizing in the chrome inspector for a live demo.
i showed some options to chelsea and the spacing of the products gets messed up.

**Comment by chelseafischerlodike** [comment]
@DevStL @peak9ine Jay and I decided to leave as is for now based on the issues we ran into.
