### ISSUE TITLE
Explore a Little More section - added functionality

### ISSUE THREAD

**Issue by chelseafischerlodike** [chelseafischerlodike/CKMK-Digital-Bella#102]
Add functionality to the Benefits section in case we want to default to a tab other than "Benefits"

**Comment by peak9ine** [comment]
@chelseafischerlodike @DevStL what's the status of this issue, I wasn't sure by the title.

**Comment by chelseafischerlodike** [comment]
@peak9ine  Jay hasn't addressed to my knowledge. It is to be able to have the flexibility to make any one of the four "tabs" defaultable. So if we wanted Nutrition to default as expanded vs Benefits.

**Comment by DevStL** [comment]
this would be a global change across the site. all products would default to the same tab to be open

**Comment by chelseafischerlodike** [comment]
@DevStL if you haven't started on this change, please disregard. moving to done column / won't fix
