### ISSUE TITLE
Review Hearts Asset (1/2 a heart)

### ISSUE THREAD

**Issue by chelseafischerlodike** [chelseafischerlodike/CKMK-Digital-Bella#106]
Give Jay a half heart PNG for 1/2 review instances (i.e., 4.5)

**Comment by ghost** [comment]
I think I have this asset already made, @DevStL are we building this similar to Amazon's review stars? Have 4 full or empty stars on either side of a half star to slide back and forth.

**Comment by DevStL** [comment]
Chelsea, can you tell me where this is an issue and i'll investigate. we shouldn't need any additional images for the ratings.

**Comment by chelseafischerlodike** [comment]
no issue currently as we don't have reviews, more so it was posed in case there was a 4.5 review for example but looks like via submission form users can only submit full stars, not halves. marking as won't fix sand moving to done column

**Comment by DevStL** [comment]
the granularity of average ratings as they are displayed by the stars are
only down to the 1/2 star. but yes, individual reviews are whole star
ratings.
we do have logic to display 1/2 star and whole star ratings on the total
review.
