### ISSUE TITLE
Pate pack category page

### ISSUE THREAD

**Issue by chelseafischerlodike** [chelseafischerlodike/CKMK-Digital-Bella#108]
This was approved by brand team, can we get in queue to develop the side by side product listing that this page includes as not currently part of the template? Lexi has whatever files you need. Thanks!

**Comment by ghost** [comment]
It looks like we can re-use the dry package page to create the variety pack page. The variety pack SKU page will probably require modifications.

**Comment by chelseafischerlodike** [comment]
Confirming there is still some styling needed here (at least more room after product copy and the Reviews bar)

**Comment by DevStL** [comment]
space added between component products and reviews bar
