### ISSUE TITLE
wrong dry pack image on Wet Turkey Page carousel

### ISSUE THREAD

**Issue by chelseafischerlodike** [chelseafischerlodike/CKMK-Digital-Bella#109]
https://stage.belladogfood.com/products/pate-wet-food/with-turkey-in-savory-juices/

We need to swap out this dry pack in the bottom carousel cards with the new dry bag (reference packages on dry page for reference)

**Comment by DevStL** [comment]
i have removed a bunch of duplicate (and confusing) product images from the media library and updated all pages with (hopefully) correct images.
