### ISSUE TITLE
Pate Pack - Also a FusePump to-do item

### ISSUE THREAD

**Issue by chelseafischerlodike** [chelseafischerlodike/CKMK-Digital-Bella#116]
We had discussed including a "Buy Online" button for the Pate Pack can we still implement this before we list the two flavors on this page?

**Comment by DevStL** [comment]
is this a fusepump link? or something else?

**Comment by chelseafischerlodike** [comment]
Yes it will be a fusepump link, still waiting on their team to provide IDs and end codes for everything including the pate pack

**Comment by DevStL** [comment]
we can put the link anywhere, we just will need to be consistent across pages.
the sooner the better on the info from fusepump.

**Comment by chelseafischerlodike** [comment]
Every page except pate pack would have the fusepump portion pop up when Where to Buy is clicked. Pate pack (since we don't have those (4) callout sections would need to live elsewhere. Is that possible? Lexi had one button centered above the two flavors in her pate pack comp.
