### ISSUE TITLE
Expand width of columns on product pages

### ISSUE THREAD

**Issue by chelseafischerlodike** [chelseafischerlodike/CKMK-Digital-Bella#25]

**Comment by DevStL** [comment]
Nick or CSS to fix

**Comment by peak9ine** [comment]
let's go with the wider width shown on this page under the "pamper" section: https://www.belladogfood.com/about-bella/ - Apply site wide

**Comment by peak9ine** [comment]
@murphyni cc'ing you on this so you are aware of making all copy block columns the same width across the site in relation to the recommended variations linked above.

**Comment by chelseafischerlodike** [comment]
@DevStL can you confirm this one is complete?

**Comment by DevStL** [comment]
i have expanded the width of the copy immediately under the product image.
if we want the tabs expanded, then @murphyni will need to make that update in CSS.
