### ISSUE TITLE
GA tagging updates

### ISSUE THREAD

**Issue by chelseafischerlodike** [chelseafischerlodike/CKMK-Digital-Bella#61]
Keely is QA'ing the tagging in place. We'll need to make those revisions.

**Comment by chelseafischerlodike** [comment]
GA Tags: update tags that are wrong (from Keely’s findings) in phase 2 of website
- Dry flavor names
- Wet flavor names
- Text under product images on both category pages (currently only the images are being tracked, not if user clicked on product name)

**Comment by chelseafischerlodike** [comment]
Jay-
Could this one be addressed within Thursday's scan (1/12)?

**Comment by DevStL** [comment]
category pages updated in dev

**Comment by chelseafischerlodike** [comment]
so all three done?
Dry flavor names
Wet flavor names
Text under product images on both category pages (currently only the images are being tracked, not if user clicked on product name)

**Comment by DevStL** [comment]
yes, all should be fixed. updated the product links to have full product name, and added tracking to product title text.
these changes are only for product category pages.
