### ISSUE TITLE
homepage image copy

### ISSUE THREAD

**Issue by chelseafischerlodike** [chelseafischerlodike/CKMK-Digital-Bella#77]
Hero image: need to add copy that says we are showing a mix of wet and dry food in the bowl (in waffle)

Copy: Food in bowl shows Bella Pate Wet and Bella Dry food

**Comment by chelseafischerlodike** [comment]
Andrew- LT is working on copy for this. Do we have an idea of placement on hero image so I can give her a suggested word count?

**Comment by chelseafischerlodike** [comment]
Copy LT wants to use is:  "Serving suggestion"

**Comment by peak9ine** [comment]
@murphyni have you looked at dropping the copy on the homepage image yet?

**Comment by ghost** [comment]
@peak9ine I did, a preview is up on the CKMK dev server. 
http://usstli1013.nestle.com:86/index.html

**Comment by peak9ine** [comment]
It's legible on desktop, not so much on mobile. Just like you anticipated. I think we may need a live text option.

**Comment by ghost** [comment]
It did get very fine on mobile, I tried our other approach of replacing the scroll more text with "Serving Suggestion" Hit the link for update.

**Comment by chelseafischerlodike** [comment]
thanks for showing us both ways, Nick! @peak9ine my concern with replacing scroll more is that "serving suggestion" gets dropped on mobile...so we aren't really solving the concern with legibility. Unless we have a recommendation we can leave it up to legal to decide which version they prefer

**Comment by peak9ine** [comment]
@chelseafischerlodike Agreed. I don't think we have the solution yet. We are going to try live text in proximity to the photo. @murphyni is working on that today.

**Comment by ghost** [comment]
Placed live text in close proximity to the bowl. It won't always be in a perfect place because it scales at a different rate than the background image.

**Comment by chelseafischerlodike** [comment]
I think this is a good solve. @peak9ine how do you think this is looking?
