### ISSUE TITLE
nurture and nourish image change

### ISSUE THREAD

**Issue by chelseafischerlodike** [chelseafischerlodike/CKMK-Digital-Bella#82]
Update image in circle within nuture and nourish section image for this section will need to be cropped in to match the shot that's currently in place.  

Asset:
BL0651_Tabletop_Dry_Loaf_0270.jpg
File Path:
078362_INET_Bella Website Strategy 2015>Amela> website>photography>assets>offers

**Comment by chelseafischerlodike** [comment]
What are specs for this piece of content? If you can provide, I can give to Jayne to resize the image.

**Comment by peak9ine** [comment]
@DevStL @murphyni can you pull specs for Chelsea?

**Comment by DevStL** [comment]
https://stage.belladogfood.com/media/1005/food.png
580px wide x 581px tall

**Comment by chelseafischerlodike** [comment]
@DevStL Jayne has provided new image in same file path above, can you please drop in this new image content?
