### ISSUE TITLE
Why Bella flourish

### ISSUE THREAD

**Issue by chelseafischerlodike** [chelseafischerlodike/CKMK-Digital-Bella#84]
Linear flourishes faded off here, need to be consistent on the whether they fade or don't fade

**Comment by DevStL** [comment]
creative and content

**Comment by peak9ine** [comment]
Let's make a decision on how to handle flourishes and apply across the entire site

**Comment by peak9ine** [comment]
Nick, can you post a demo link here and put this in the review column?

**Comment by ghost** [comment]
Below is a link to several executions for flourishes. The "SVG Drawing" example is our recommendation. Link only works if you are hardwired to Nestle's network.

http://usstli1013.nestle.com:86/test-animations.html

**Comment by peak9ine** [comment]
@chelseafischerlodike we mark this as done now that we have an approved demo / direction
