### ISSUE TITLE
offers page product carousel dry bag

### ISSUE THREAD

**Issue by chelseafischerlodike** [chelseafischerlodike/CKMK-Digital-Bella#86]
Dry package on product carousel is the incorrect package

**Comment by DevStL** [comment]
this should be updated now?

**Comment by chelseafischerlodike** [comment]
product in carousel is old packaing. notice different dog than the bag in header image. if you can give me specs I'll get a new image

**Comment by chelseafischerlodike** [comment]
Can you give me specs for this and I'll have Jayne resize correct package?

**Comment by DevStL** [comment]
is this the correct bag? https://stage.belladogfood.com/offers/
https://stage.belladogfood.com/media/1133/dry_beef.png

**Comment by chelseafischerlodike** [comment]
yes correct bag, thank you!
