### ISSUE TITLE
pate wet category page - code

### ISSUE THREAD

**Issue by chelseafischerlodike** [chelseafischerlodike/CKMK-Digital-Bella#87]
Reviews anchor should have a trailing #readReviews to take users to the reviews section on page load

**Comment by DevStL** [comment]
reviews anchor have a "writeReview" anchor that performs this function. does it need to say "readReviews"?

**Comment by ghost** [comment]
I wrote a function to open the reviews drawer if the url is trailing "#readReviews"

We should change the script to "#writeReview" or modify the url to "#readReviews"

**Comment by peak9ine** [comment]
@murphyni is this ready to Demo/Review?

**Comment by DevStL** [comment]
this was causing issues on the category page when clicking on the product reviews link. the page would scroll down to the reviews section of the category page, then navigate to the product page, and not move to the reviews section of the newly loaded page.

**Comment by chelseafischerlodike** [comment]
@DevStL @murphyni @peak9ine Jay- do you need something additional from Nick to finish or has it been handled?

**Comment by ghost** [comment]
Now that we have added reviews to the product category page, this function will no longer work. I will remove.
