### ISSUE TITLE
Flourishes need new file

### ISSUE THREAD

**Issue by chelseafischerlodike** [chelseafischerlodike/CKMK-Digital-Bella#93]
Update all flourish files so that there is not a white fuzzy edge on black line after it has animated

**Comment by DevStL** [comment]
this is all content.
new files to be created by designer

**Comment by ghost** [comment]
This is a component Gregory did, not sure if or where those working files were saved.

**Comment by chelseafischerlodike** [comment]
Thanks! We'll figure out how Andrew wants to handle when we regroup tomorrow. Appreciate you taking a look!

**Comment by peak9ine** [comment]
Let's try the options discussed in our session. Set up a module on a new page to test / compare options. link each on this issue thread to review.

**Comment by chelseafischerlodike** [comment]
the about page example Nick shared looks great

**Comment by peak9ine** [comment]
@chelseafischerlodike we need John G to go through all the instances of flourishes and deliver a consistent file for Nick's SVG needs. Let's set up a meeting between the 4 of us to go over the SVG flourish set process.

**Comment by peak9ine** [comment]
@murphyni New flourishes SVG files are ready. Hopefully the file name tells your where to drop them, if not ask. I made some updates. Not all are an exact match from the live site. I went for consistency.
