### ISSUE TITLE
offers page & about bella page - backgrounds

### ISSUE THREAD

**Issue by chelseafischerlodike** [chelseafischerlodike/CKMK-Digital-Bella#95]
On the sign up page and the about Bella page, the patterned backgrounds seem to missing some of lighter, white shapes within the pattern. more similar to the category page patterns.

**Comment by peak9ine** [comment]
@murphyni Can you look into this issue?

**Comment by ghost** [comment]
@peak9ine @chelseafischerlodike I looked at the original .psd files and they did not have white accents in the hero patterns. You want me to add white accents?

**Comment by chelseafischerlodike** [comment]
@murphyni @peak9ine this was amela's feedback. Andrew- please let Nick know if you feel like this needs to be addressed or if we can remove this issue.

**Comment by peak9ine** [comment]
@murphyni let me pull up the comp and see what's missing.

**Comment by peak9ine** [comment]
@chelseafischerlodike The artwork in the psd comps don't have the white translucent overlay as mentioned. The creative files reflect what's live. If we'd like to update this we need to have the brand team supply a new wallpaper. I'm going to tag this as "wontfix" and we can open a new ticket for design if necessary.

**Comment by chelseafischerlodike** [comment]
I'm fine with that! @peak9ine  thank you!
